[package]
name = "oprec"
version = "0.1.0"
authors = ["flurpdadurp@gmail.com"]
description = "Calculus crate that analyzes and transforms mathematical functions."

[dependencies]
petgraph = "0.4.10"
rand = "0.4"
